"""Dictionaries: dim_region (+ ml/configs/regions.yaml), dim_profile, dim_organization, ersb_snapshot."""

import csv
from pathlib import Path

import duckdb
import pandas as pd
import yaml
from rapidfuzz import fuzz, process

from hqai_ml.ingest.config import IngestParams
from hqai_ml.ingest.normalize import core_key, name_key, number_tokens

# Official KATO 2-digit region codes, for human review in regions.yaml only.
# NOT used for the mapping (the mapping is derived from the data).
KATO_REFERENCE = {
    "10": "Абайская область",
    "11": "Акмолинская область",
    "15": "Актюбинская область",
    "19": "Алматинская область",
    "23": "Атырауская область",
    "27": "Западно-Казахстанская область",
    "31": "Жамбылская область",
    "33": "Жетысуская область",
    "35": "Карагандинская область",
    "39": "Костанайская область",
    "43": "Кызылординская область",
    "47": "Мангистауская область",
    "55": "Павлодарская область",
    "59": "Северо-Казахстанская область",
    "61": "Туркестанская область",
    "62": "Улытауская область",
    "63": "Восточно-Казахстанская область",
    "71": "г. Астана",
    "75": "г. Алматы",
    "79": "г. Шымкент",
}

REGIONS_YAML_HEADER = """\
# dim_region: numeric region code (dataset 2 region_origin_code / hospitalization_code part 1)
# -> region name as spelled in dataset 3 (normalized).
#
# Generated by ml/pipelines/ingest.py from a referral-weighted majority vote:
# every dataset-1 referral with code C votes for the dataset-3 region_in of its hospital
# (hospital names matched on the normalized key).
#
# HOW TO FIX MANUALLY: edit `name` and set `manual_override: true` — the next ingest run keeps it.
# `aliases`: extra spellings (e.g. historical names) that should map to this code in dataset 3.
# `ambiguous: true` means the winner got less than `min_share` of the votes — please review.
# `kato_reference` is a hint from the official KATO classifier; it is not used by the pipeline.
"""


# ------------------------------------------------------------------ dim_profile
# Majority votes below use arg_max(value, struct_pack(n, value)): on equal counts the larger value wins, so every
# ingest assigns the same names and regions (a plain arg_max(value, n) picks an arbitrary one of the tied values —
# 5 hospitals have tied region-prefix votes).


def build_dim_profile(con: duckdb.DuckDBPyConnection, p: IngestParams) -> None:
    con.execute(
        """CREATE OR REPLACE TABLE dim_profile AS
        WITH x AS (SELECT profile_code, bed_profile, count(*) AS n FROM stg_referral GROUP BY ALL),
        t AS (
            SELECT profile_code,
                   sum(n) AS n_referrals,
                   arg_max(bed_profile, struct_pack(n := n, tie := bed_profile))
                       FILTER (WHERE bed_profile IS NOT NULL) AS top_name,
                   max(n) FILTER (WHERE bed_profile IS NOT NULL) AS top_n,
                   sum(n) FILTER (WHERE bed_profile IS NOT NULL) AS named_n
            FROM x GROUP BY profile_code)
        SELECT profile_code,
               CASE WHEN profile_code = $dh THEN $dh_name ELSE top_name END AS profile_name,
               CASE WHEN profile_code = $dh THEN NULL ELSE top_n / named_n END AS name_share,
               CAST(n_referrals AS INTEGER) AS n_referrals,
               profile_code = $dh AS is_day_hospital
        FROM t ORDER BY profile_code""",
        {"dh": p.day_hospital_code, "dh_name": p.day_hospital_name},
    )


# ------------------------------------------------------------------- dim_region
def _load_regions_yaml(path: Path) -> dict:
    if not path.exists():
        return {}
    data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    return {str(k): v for k, v in (data.get("regions") or {}).items()}


def build_dim_region(
    con: duckdb.DuckDBPyConnection, p: IngestParams, regions_yaml: Path, waiting_codes: list[str]
) -> dict:
    votes = con.execute(
        """WITH hosp_region AS (      -- each dataset-3 hospital key -> its (majority) region name
               SELECT org_in_key, arg_max(region_in, struct_pack(n := n, tie := region_in)) AS region_in
               FROM (SELECT org_in_key, region_in, count(*) n FROM stg_refusal
                     WHERE org_in_key IS NOT NULL AND region_in IS NOT NULL GROUP BY ALL)
               GROUP BY org_in_key)
           SELECT r.region_code, h.region_in, count(*) AS v
           FROM stg_referral r JOIN hosp_region h ON h.org_in_key = r.hospital_key
           GROUP BY ALL"""
    ).fetchdf()
    ref_codes = [r[0] for r in con.execute("SELECT DISTINCT region_code FROM stg_referral").fetchall()]
    codes = sorted(set(waiting_codes) | set(ref_codes))
    existing = _load_regions_yaml(regions_yaml)

    rows, out = [], {}
    for code in codes:
        v = votes[votes.region_code == code].sort_values("v", ascending=False)
        total = int(v.v.sum())
        top = v.iloc[0] if total else None
        second = v.iloc[1] if len(v) > 1 else None
        vote_name = top.region_in if top is not None else None
        share = float(top.v / total) if total else None
        ambiguous = share is None or share < p.region_vote_min_share
        prev = existing.get(code, {})
        manual = bool(prev.get("manual_override", False))
        name = prev.get("name") if manual and prev.get("name") else (vote_name or f"(unknown region {code})")
        aliases = list(prev.get("aliases") or [])
        out[code] = {
            "name": name,
            "manual_override": manual,
            "ambiguous": ambiguous,
            "vote": {
                "name": vote_name,
                "share": round(share, 3) if share is not None else None,
                "referrals_voted": total,
                "runner_up": second.region_in if second is not None else None,
                "runner_up_share": round(float(second.v / total), 3) if second is not None else None,
            },
            "aliases": aliases,
            "in_dataset2": code in waiting_codes,
            "kato_reference": KATO_REFERENCE.get(code),
        }
        rows.append(
            {
                "region_code": code,
                "region_name": name,
                "vote_region_name": vote_name,
                "vote_share": share,
                "vote_referrals": total,
                "runner_up_name": out[code]["vote"]["runner_up"],
                "runner_up_share": out[code]["vote"]["runner_up_share"],
                "is_ambiguous": ambiguous,
                "manual_override": manual,
            }
        )

    body = yaml.safe_dump(
        {"min_share": p.region_vote_min_share, "regions": out}, allow_unicode=True, sort_keys=False, width=120
    )
    regions_yaml.write_text(REGIONS_YAML_HEADER + "\n" + body, encoding="utf-8")

    df = pd.DataFrame(rows)
    con.register("_dim_region_df", df)
    con.execute(
        """CREATE OR REPLACE TABLE dim_region AS SELECT
               region_code::VARCHAR AS region_code, region_name::VARCHAR AS region_name,
               vote_region_name::VARCHAR AS vote_region_name, vote_share::DOUBLE AS vote_share,
               vote_referrals::INTEGER AS vote_referrals, runner_up_name::VARCHAR AS runner_up_name,
               runner_up_share::DOUBLE AS runner_up_share, is_ambiguous::BOOLEAN AS is_ambiguous,
               manual_override::BOOLEAN AS manual_override
           FROM _dim_region_df ORDER BY region_code"""
    )
    con.unregister("_dim_region_df")

    # lookup used to map dataset-3 region names (and aliases) to codes
    lookup = [(name_key(r["name"]), c) for c, r in out.items() if r["name"]]
    lookup += [(name_key(a), c) for c, r in out.items() for a in r["aliases"]]
    names_per_code = pd.DataFrame(lookup, columns=["key", "region_code"]).drop_duplicates()
    collisions = names_per_code[names_per_code.duplicated("key", keep=False)]
    con.register("_region_lookup_df", names_per_code.drop_duplicates("key"))
    con.execute(
        "CREATE OR REPLACE TABLE region_lookup AS SELECT key::VARCHAR AS key, region_code::VARCHAR AS region_code "
        "FROM _region_lookup_df"
    )
    con.unregister("_region_lookup_df")
    return {
        "codes": len(codes),
        "ambiguous": [c for c, r in out.items() if r["ambiguous"]],
        "manual_overrides": [c for c, r in out.items() if r["manual_override"]],
        "name_collisions": sorted(collisions.key.unique().tolist()),
    }


# ------------------------------------------------------------- dim_organization
def build_dim_organization(
    con: duckdb.DuckDBPyConnection, p: IngestParams, matching_csv: Path, overrides_yaml: Path
) -> dict:
    con.execute(
        """CREATE OR REPLACE TABLE stg_org AS
        WITH names AS (SELECT org_code, hospital_mo, hospital_key, count(*) n FROM stg_referral GROUP BY ALL),
        prefixes AS (SELECT org_code, region_code, count(*) n FROM stg_referral GROUP BY ALL),
        hosp_region AS (
            SELECT org_in_key, arg_max(region_code, struct_pack(n := n, tie := region_code)) AS region_code
            FROM (SELECT org_in_key, l.region_code, count(*) n FROM stg_refusal s
                  JOIN region_lookup l ON l.key = s.region_in_key GROUP BY ALL)
            GROUP BY org_in_key)
        SELECT o.org_code, o.org_name, o.org_key, o.n_referrals, pr.n_origin_regions,
               coalesce(hr.region_code, pr.top_prefix) AS region_code,
               CASE WHEN hr.region_code IS NOT NULL THEN 'admission_refusals_region'
                    ELSE 'majority_origin_prefix' END AS region_method
        FROM (SELECT org_code, top.name AS org_name, top.key AS org_key, n_referrals
              FROM (SELECT org_code, arg_max(struct_pack(name := hospital_mo, key := hospital_key),
                                   struct_pack(n := n, tie := hospital_mo, tie_key := hospital_key)) AS top,
                           CAST(sum(n) AS INTEGER) AS n_referrals
                    FROM names GROUP BY org_code)) o
        JOIN (SELECT org_code, CAST(count(*) AS INTEGER) n_origin_regions,
                     arg_max(region_code, struct_pack(n := n, tie := region_code)) top_prefix
              FROM prefixes GROUP BY org_code) pr USING (org_code)
        LEFT JOIN hosp_region hr ON hr.org_in_key = o.org_key"""
    )

    orgs = con.execute("SELECT org_code, org_name, org_key, n_referrals FROM stg_org").fetchdf()
    ersb = con.execute(
        "SELECT ersb_id, org_name, org_key, discharged_total FROM stg_ersb WHERE org_key IS NOT NULL"
    ).fetchdf()
    # exact key -> ERSB row with the largest discharged_total (ERSB has a few duplicate names)
    exact = ersb.sort_values(["discharged_total", "ersb_id"], ascending=[False, True]).drop_duplicates("org_key")
    exact_by_key = dict(zip(exact.org_key, exact.ersb_id, strict=True))
    ersb_cores = [core_key(k) for k in ersb.org_key]
    ersb_rows = ersb.to_dict("records")

    matches, fuzzy_rows = [], []
    for o in orgs.itertuples():
        if o.org_key in exact_by_key:
            matches.append((o.org_code, int(exact_by_key[o.org_key]), 100.0, "exact"))
            continue
        core = core_key(o.org_key)
        cands = process.extract(core, ersb_cores, scorer=fuzz.token_set_ratio, score_cutoff=p.fuzzy_min_score, limit=10)
        scored = []
        for cand_core, set_score, idx in cands:
            sort_score = fuzz.token_sort_ratio(core, cand_core)
            reasons = []
            if number_tokens(core) != number_tokens(cand_core):
                reasons.append("different numbers")
            if sort_score < p.fuzzy_min_sort_score:
                reasons.append(f"token_sort_ratio < {p.fuzzy_min_sort_score:g}")
            scored.append((not reasons, sort_score, set_score, idx, "; ".join(reasons)))
        accepted = [s for s in scored if s[0]]
        best = max(accepted, default=None, key=lambda s: (s[1], s[2]))
        if best:
            matches.append((o.org_code, int(ersb_rows[best[3]]["ersb_id"]), float(best[2]), "fuzzy"))
        else:
            matches.append((o.org_code, None, None, None))
        # review file: the accepted match, or the best rejected near-miss
        shown = best or max(scored, default=None, key=lambda s: (s[2], s[1]))
        if shown:
            row = ersb_rows[shown[3]]
            fuzzy_rows.append(
                {
                    "decision": "accepted" if shown[0] else "rejected",
                    "reject_reason": shown[4],
                    "org_code": o.org_code,
                    "org_name": o.org_name,
                    "n_referrals": o.n_referrals,
                    "ersb_id": int(row["ersb_id"]),
                    "ersb_name": row["org_name"],
                    "ersb_discharged_total": int(row["discharged_total"]),
                    "token_set_ratio": round(shown[2], 1),
                    "token_sort_ratio": round(shown[1], 1),
                    "candidates_above_set_threshold": len(cands),
                }
            )

    # manual overrides (ml/configs/org_matches.yaml) win over the automatic result
    overrides = load_org_overrides(overrides_yaml, set(orgs.org_code), {int(i) for i in ersb.ersb_id})
    ersb_name = dict(zip(ersb.ersb_id.astype(int), ersb.org_name, strict=True))
    review_by_org = {r["org_code"]: r for r in fuzzy_rows}
    applied = {"accept": 0, "reject": set()}
    for i, (org_code, ersb_id, _score, _method) in enumerate(matches):
        if org_code in overrides["accept"]:
            new_id, note = overrides["accept"][org_code]
            matches[i] = (org_code, new_id, None, "manual")
            applied["accept"] += 1
            decision, reason, shown_id = "manual_accept", note, new_id
        elif (org_code, ersb_id) in overrides["reject"]:
            # the rejected pair is removed; the hospital stays unmatched (no fallback to the next candidate)
            matches[i] = (org_code, None, None, "manual")
            applied["reject"].add((org_code, ersb_id))
            decision, reason, shown_id = "manual_reject", overrides["reject"][(org_code, ersb_id)], ersb_id
        else:
            continue
        row = review_by_org.setdefault(org_code, {"org_code": org_code})
        row.update(
            {"decision": decision, "reject_reason": reason, "ersb_id": shown_id, "ersb_name": ersb_name[shown_id]}
        )
    fuzzy_rows = list(review_by_org.values())

    con.register("_org_match_df", pd.DataFrame(matches, columns=["org_code", "ersb_id", "match_score", "match_method"]))
    con.execute(
        """CREATE OR REPLACE TABLE dim_organization AS
        SELECT o.org_code, o.org_name, o.org_key, o.region_code, o.region_method,
               o.n_referrals, o.n_origin_regions,
               CAST(m.ersb_id AS INTEGER) AS ersb_id, CAST(m.match_score AS DOUBLE) AS match_score,
               CAST(m.match_method AS VARCHAR) AS match_method
        FROM stg_org o JOIN _org_match_df m USING (org_code)
        ORDER BY o.org_code"""
    )
    con.unregister("_org_match_df")

    matching_csv.parent.mkdir(parents=True, exist_ok=True)
    fuzzy_rows.sort(key=lambda r: (r["decision"], r.get("token_set_ratio") or 0, r.get("token_sort_ratio") or 0))
    fields = [
        "decision",
        "reject_reason",
        "org_code",
        "org_name",
        "n_referrals",
        "ersb_id",
        "ersb_name",
        "ersb_discharged_total",
        "token_set_ratio",
        "token_sort_ratio",
        "candidates_above_set_threshold",
    ]
    with open(matching_csv, "w", newline="", encoding="utf-8-sig") as f:
        w = csv.DictWriter(f, fieldnames=fields, restval="")
        w.writeheader()
        w.writerows(fuzzy_rows)

    stats = con.execute(
        """SELECT count(*), count(*) FILTER (WHERE match_method = 'exact'),
                   count(*) FILTER (WHERE match_method = 'fuzzy'),
                  count(*) FILTER (WHERE ersb_id IS NULL),
                  count(*) FILTER (WHERE region_method = 'admission_refusals_region'),
                  count(*) FILTER (WHERE match_method = 'manual')
           FROM dim_organization"""
    ).fetchone()
    return {
        "orgs": stats[0],
        "ersb_exact": stats[1],
        "ersb_fuzzy": stats[2],
        "ersb_unmatched": stats[3],
        "region_from_admission_refusals": stats[4],
        "ersb_manual": stats[5],
        "manual_accepts_applied": applied["accept"],
        "manual_rejects_applied": len(applied["reject"]),
        # rejects whose pair the automatic matching did not produce this run (kept as guards)
        "manual_rejects_not_triggered": sorted(
            f"{o}->{e}" for o, e in overrides["reject"] if (o, e) not in applied["reject"]
        ),
        "fuzzy_rejected_near_misses": sum(r["decision"] == "rejected" for r in fuzzy_rows),
    }


def load_org_overrides(path: Path, org_codes: set[str], ersb_ids: set[int]) -> dict:
    """Read ml/configs/org_matches.yaml; fail loudly on unknown codes/ids or contradictory entries."""
    result: dict = {"accept": {}, "reject": {}}
    if not path.exists():
        return result
    data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    errors = []
    for kind in ("accept", "reject"):
        for entry in data.get(kind) or []:
            org_code, ersb_id, note = str(entry.get("org_code", "")), entry.get("ersb_id"), entry.get("note") or ""
            if org_code not in org_codes:
                errors.append(f"{kind}: unknown org_code {org_code!r}")
            if not isinstance(ersb_id, int) or ersb_id not in ersb_ids:
                errors.append(f"{kind}: unknown ersb_id {ersb_id!r} (org_code {org_code})")
            if kind == "accept":
                if org_code in result["accept"] and result["accept"][org_code][0] != ersb_id:
                    errors.append(f"accept: org_code {org_code} accepted for two different ersb_ids")
                result["accept"][org_code] = (ersb_id, note)
            else:
                result["reject"][(org_code, ersb_id)] = note
    for org_code, (ersb_id, _) in result["accept"].items():
        if (org_code, ersb_id) in result["reject"]:
            errors.append(f"{org_code} -> {ersb_id} is both accepted and rejected")
    if errors:
        raise ValueError(f"{path}: " + "; ".join(errors))
    return result


def build_ersb_snapshot(con: duckdb.DuckDBPyConnection) -> None:
    con.execute(
        """CREATE OR REPLACE TABLE ersb_snapshot AS
        WITH m AS (
            SELECT ersb_id, org_code,
                   count(*) OVER (PARTITION BY ersb_id) AS n_matched,
                   row_number() OVER (PARTITION BY ersb_id ORDER BY match_score DESC, n_referrals DESC, org_code) AS rk
            FROM dim_organization WHERE ersb_id IS NOT NULL)
        SELECT e.ersb_id, e.org_name, e.org_key,
               e.discharged_total, e.discharged_children, e.treated_budget, e.treated_paid,
               e.discharged_within_day, e.deaths_total, e.bed_days, e.amount_to_pay,
               CASE WHEN e.discharged_total > 0 THEN e.bed_days / e.discharged_total END AS avg_length_of_stay,
               m.org_code,
               CAST(coalesce(m.n_matched, 0) AS INTEGER) AS n_matched_org_codes,
               e.sdu_load_date
        FROM stg_ersb e LEFT JOIN m ON m.ersb_id = e.ersb_id AND m.rk = 1
        ORDER BY e.ersb_id"""
    )


# ---------------------------------------------------------------------- dim_icd
def build_dim_icd(con: duckdb.DuckDBPyConnection) -> dict:
    """ICD-10 code -> Russian name, from the names the source systems attach to each code.

    There is no official ICD dictionary in the open data. For every code the most frequent spelling across
    dataset 1 (referral diagnosis) and dataset 3 (admission-refusal diagnosis) is kept; name_share says how
    dominant it is (1.0 = every row agrees). Codes are upper-case as in the facts (e.g. "O80.0", "M42").
    """
    con.execute(
        """CREATE OR REPLACE TABLE dim_icd AS
        WITH names AS (
            SELECT icd10_code, diagnosis_name AS name, 'referral' AS source FROM stg_referral
            UNION ALL
            SELECT icd10_code, icd_name, 'refusal' FROM stg_refusal
        ),
        counted AS (
            SELECT icd10_code, name, count(*) AS n FROM names
            WHERE icd10_code IS NOT NULL AND name IS NOT NULL GROUP BY ALL
        ),
        ranked AS (  -- most frequent spelling first; ties broken by the name itself, so reruns agree
            SELECT *, row_number() OVER (PARTITION BY icd10_code ORDER BY n DESC, name) AS rk,
                   sum(n) OVER (PARTITION BY icd10_code) AS named_n
            FROM counted
        ),
        per_code AS (SELECT icd10_code, name AS icd10_name, n AS top_n, named_n FROM ranked WHERE rk = 1),
        referrals AS (SELECT icd10_code, count(*) AS n FROM stg_referral WHERE icd10_code IS NOT NULL GROUP BY ALL)
        SELECT c.icd10_code::VARCHAR AS icd10_code,
               c.icd10_name::VARCHAR AS icd10_name,
               c.top_n / c.named_n AS name_share,
               CAST(coalesce(r.n, 0) AS INTEGER) AS n_referrals
        FROM per_code c LEFT JOIN referrals r USING (icd10_code)
        ORDER BY c.icd10_code"""
    )
    rows, exact3 = con.execute(
        "SELECT count(*), count(*) FILTER (WHERE length(icd10_code) = 3) FROM dim_icd"
    ).fetchone()
    return {"codes": rows, "three_character_codes": exact3}
