/** Synthetic API DTO fixtures. No ML artifacts are read or regenerated. */
import type {
  ModelAssuranceCapabilityResponse,
  ModelAssuranceSnapshotResponse,
  OperationalForecastResponse,
  OperationalOverviewResponse,
  OperationalSignalResponse,
  SignalExplanationResponse,
} from "../api/generated";

export const identity = "a".repeat(64);
const source = {
  run_id: "fixture-flow",
  scientific_identity_sha256: "b".repeat(64),
  artifact_sha256: "c".repeat(64),
  dataset_identity_sha256: null,
  config_identity_sha256: null,
  code_identity_sha256: null,
};
export const counts = {
  total_signals: 3,
  high: 1,
  elevated: 1,
  watch: 0,
  normal: 0,
  unsupported_severity: 1,
  preventive_pressure: 3,
  observed_unusual_flow: 0,
  direct_supported: 1,
  fallback_limited: 1,
  unsupported_support: 1,
  calibrated: 2,
  uncertainty_limited_or_unavailable: 1,
};
export const overview: OperationalOverviewResponse = {
  snapshot: {
    publication_id: "fixture-publication",
    schema_version: "operational_intelligence_v1",
    contract_version: "1.0.0",
    publication_identity_sha256: identity,
    bundle_sha256: identity,
    assurance_identity_sha256: identity,
    source_code_commit: "d".repeat(40),
    current_origin: "2025-03-31",
    freshness_state: "UNKNOWN",
    publication_status: "AVAILABLE",
    generated_at: null,
    published_at: "2026-09-22T18:00:00Z",
    forecast_count: 3,
    signal_count: 3,
    source_provenance: { flow_forecast: source },
    limitations: ["Исторический срез; не данные в реальном времени."],
  },
  national: counts,
  regions: [{ region_code: "71", counts }],
};
export const signal: OperationalSignalResponse = {
  signal_id: "pressure-1",
  signal_type: "preventive_flow_pressure",
  series_id: "hospital-ZIQ9-241",
  origin: "2025-03-31",
  target: "registrations",
  org_code: "ZIQ9",
  region_code: "71",
  profile_code: "241",
  inbox_rank: 7,
  severity: "HIGH",
  headline: "Поток выше исторического ориентира",
  concise_reason: "Прогноз пересекает исторический ориентир 10.",
  materiality_status: "MATERIAL",
  support_status: "DIRECT_SUPPORTED",
  fallback_status: "NOT_APPLICABLE",
  uncertainty_status: "CALIBRATED",
  pressure_basis: "historical_flow_proxy_v1",
  threshold_value: 10,
  threshold_status: "SUPPORTED",
  forecast_value: 15,
  uncertainty_lower: 11,
  uncertainty_upper: 19,
  first_crossing_date: "2025-04-01",
  lead_time_days: 1,
  observed_anomaly_status: null,
  observed_anomaly_present: false,
  data_freshness: "2025-03-31",
  reason_codes: ["FORECAST_ABOVE_REFERENCE"],
  evidence_facts: ["Центральный прогноз: 15 регистраций."],
  provenance_keys: ["flow_forecast"],
  anomaly_evidence: null,
  limitations: ["Вместимость не проверялась."],
  publication_identity_sha256: identity,
  source_provenance: { flow_forecast: source },
};
export const signals: OperationalSignalResponse[] = [
  signal,
  {
    ...signal,
    signal_id: "pressure-2",
    inbox_rank: 12,
    severity: "ELEVATED",
    headline: "Региональный резервный прогноз",
    support_status: "FALLBACK_LIMITED",
    fallback_status: "REGION_PROFILE_FALLBACK",
  },
  {
    ...signal,
    signal_id: "pressure-3",
    inbox_rank: null,
    severity: "UNSUPPORTED",
    headline: "Недостаточная поддержка",
    support_status: "UNSUPPORTED",
    fallback_status: "UNSUPPORTED",
    uncertainty_status: "UNAVAILABLE",
    uncertainty_lower: null,
    uncertainty_upper: null,
    forecast_value: null,
  },
];
export const forecast: OperationalForecastResponse = {
  series_id: signal.series_id,
  level: "hospital",
  origin: signal.origin,
  target_date: "2025-04-01",
  horizon: 1,
  target: "registrations",
  org_code: signal.org_code,
  region_code: signal.region_code,
  profile_code: signal.profile_code,
  central_value: 15,
  central_semantics: "P50",
  raw_quantiles: {
    p10: 12,
    p50: 15,
    p90: 18,
    semantics: "UNCHANGED_MODEL_EVIDENCE",
  },
  calibrated_uncertainty: {
    lower: 11,
    upper: 19,
    nominal_coverage: 0.8,
    calibration_status: "CALIBRATED",
    support_class: "SUPPORTED",
    calibration_version: "fixture-v1",
  },
  calibration_status: "CALIBRATED",
  prediction_source: "DIRECT",
  hierarchy_status: "COHERENT",
  support_status: "DIRECT_SUPPORTED",
  fallback_status: "NOT_APPLICABLE",
  uncertainty_status: "CALIBRATED",
  provenance_keys: ["flow_forecast"],
  evidence_facts: [],
  limitations: ["Интервал не гарантирует исход."],
  publication_identity_sha256: identity,
  source_provenance: { flow_forecast: source },
};
export const explanation: SignalExplanationResponse = {
  subject: {
    signal_id: signal.signal_id,
    signal_type: signal.signal_type,
    series_id: signal.series_id,
    target: signal.target,
    origin: signal.origin,
    org_code: "ZIQ9",
    region_code: "71",
    profile_code: "241",
    severity: signal.severity,
    inbox_rank: 7,
  },
  summary: "Опубликованный прогноз пересёк исторический ориентир.",
  why_flagged: [signal.concise_reason],
  key_evidence: [
    { code: "FORECAST", statement: "Центральный прогноз", value: 15 },
  ],
  uncertainty: {
    status: "CALIBRATED",
    narrative: "Калиброванный интервал: от 11 до 19.",
    central_value: 15,
    central_semantics: "P50",
    target_date: "2025-04-01",
    horizon_days: 1,
    raw_quantiles: forecast.raw_quantiles!,
    calibrated_lower: 11,
    calibrated_upper: 19,
    nominal_coverage: 0.8,
    calibration_status: "CALIBRATED",
  },
  support: {
    status: "DIRECT_SUPPORTED",
    fallback_status: "NOT_APPLICABLE",
    prediction_source: "DIRECT",
    narrative: "Прямая поддержка опубликованными данными.",
  },
  limitations: ["Объяснение не устанавливает причинность."],
  suggested_review_questions: ["Проверены ли исходные данные?"],
  provenance: {
    publication_id: overview.snapshot.publication_id,
    publication_identity_sha256: identity,
    assurance_identity_sha256: identity,
    source_provenance: { flow_forecast: source },
    model_assurance_capabilities: [
      {
        capability_id: "flow_point_forecast",
        evidence_status: "ACCEPTED",
        acceptance_verdict: "ACCEPT",
        product_consumption_status: "ELIGIBLE_AFTER_INGESTION",
        human_review_required: true,
        autonomous_action: false,
        capacity_checked: false,
        causal_effect_claimed: false,
      },
    ],
  },
  generation_mode: "DETERMINISTIC",
};
const unknownIdentity = {
  status: "UNKNOWN" as const,
  value: null,
  reason: "Not part of this fixture",
};
export const capability: ModelAssuranceCapabilityResponse = {
  capability_id: "flow_point_forecast",
  display_name: "Flow Forecast",
  evidence_status: "ACCEPTED",
  acceptance_verdict: "ACCEPT_WITH_P2",
  product_consumption_status: "ELIGIBLE_AFTER_INGESTION",
  identities: {
    run_id: {
      status: "AVAILABLE",
      value: "fixture-flow",
      reason: "Published run",
    },
    scientific_identity_sha256: unknownIdentity,
    artifact_sha256: unknownIdentity,
    dataset_identity_sha256: unknownIdentity,
    config_identity_sha256: unknownIdentity,
    code_identity_sha256: unknownIdentity,
    model_identity: unknownIdentity,
    estimand_id: unknownIdentity,
    calibration_identity: unknownIdentity,
    hierarchy_identity: unknownIdentity,
    pressure_provider_identity: unknownIdentity,
    prioritization_identity: unknownIdentity,
    scenario_identity: unknownIdentity,
    decision_alternative_identity: unknownIdentity,
  },
  support: {
    support_semantics: ["DIRECT_SUPPORTED", "FALLBACK_LIMITED", "UNSUPPORTED"],
    range_semantics: ["COMPLETE", "RANGE_LIMITED"],
  },
  governance: {
    human_review_required: true,
    autonomous_action: false,
    capacity_checked: false,
    causal_effect_claimed: false,
    serving_claim: false,
    physical_feasibility_status: "NOT_VALIDATED",
    promotion_status: "NO_PROMOTION",
  },
  freshness: { state: "UNKNOWN", reason: "SLA не установлен." },
  evidence: {},
  limitations: ["Только опубликованная популяция."],
  allowed_claims: ["Forecast evidence for human review"],
  forbidden_claims: [],
};
export const capabilities: ModelAssuranceCapabilityResponse[] = [
  capability,
  {
    ...capability,
    capability_id: "decision_alternatives",
    display_name: "Decision Alternatives",
    acceptance_verdict: "ACCEPT",
    product_consumption_status: "EVALUATION_ONLY",
  },
  {
    ...capability,
    capability_id: "patient_journey_competing_risk_ml_challenger",
    display_name: "Rejected Challenger",
    evidence_status: "REJECTED",
    acceptance_verdict: "DO_NOT_PROMOTE",
    product_consumption_status: "NOT_FOR_PRODUCT",
  },
];
export const assurance: ModelAssuranceSnapshotResponse = {
  assurance_id: "fixture-assurance",
  contract_version: "1.0.0",
  schema_version: "model_assurance_v1",
  assurance_identity_sha256: identity,
  bundle_sha256: identity,
  source_code_commit: "d".repeat(40),
  ml_freeze_status: "ML_CORE_CLOSED_FROZEN",
  product_contract_version: "1.0.0",
  generated_at: null,
  published_at: "2026-09-22T18:00:00Z",
  is_active: true,
  capability_count: 3,
  failed_evidence_history: [],
  claim_boundaries: {},
  monitoring_expectations: [],
  freshness_policy: {},
};
